# Generated by Django 4.0.2 on 2022-02-09 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Nome da pessoa')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail da pessoa')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Nome do produto')),
                ('section', models.CharField(default='', max_length=100, verbose_name='Seção do produto')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Preço do produto')),
                ('suggested_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Link sugerido')),
                ('status', models.IntegerField(choices=[(1, 'Reservar'), (2, 'Reservado'), (3, 'Comprado')], default=1, verbose_name='Status do produto')),
                ('image', models.ImageField(blank=True, default='', upload_to='products/images/', verbose_name='Imagem do produto')),
                ('qr_code', models.BooleanField(default=False, verbose_name='Código QR')),
                ('current_reservations', models.PositiveSmallIntegerField(default=0, verbose_name='Reservas atuais')),
                ('reservation_limit', models.PositiveSmallIntegerField(default=1, verbose_name='Limite de reservas')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='products.person', verbose_name='Reservado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='products.product', verbose_name='Produto reservado')),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservations',
            },
        ),
    ]
