# Generated by Django 4.0.2 on 2022-02-09 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='person',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='product',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
