# Generated by Django 4.0.2 on 2022-02-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_isolating_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsection',
            options={'verbose_name': 'product section', 'verbose_name_plural': 'product sections'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='current_reservations',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reservation_limit',
        ),
        migrations.AddField(
            model_name='product',
            name='bought',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de compras'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_limit',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Limite de compras'),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de reservas'),
        ),
        migrations.AlterField(
            model_name='productsection',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Seção do Produto'),
        ),
    ]
