# Generated by Django 4.0.2 on 2022-02-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_status',
            field=models.IntegerField(choices=[(1, 'Confirmado'), (2, 'Pensando')], default=1, verbose_name='Status da reserva'),
            preserve_default=False,
        ),
    ]
