# Generated by Django 4.0.2 on 2022-02-10 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_isolating_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Seção do Produto')),
            ],
            options={
                'verbose_name': 'product sections',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productsection', verbose_name='Seção do produto'),
        ),
    ]
